name: txm
channels:
  - conda-forge
  - spectrocat
  - defaults
dependencies:
  - _libavif_api=1.3.0
  - _openmp_mutex=4.5
  - anyio=4.11.0
  - aom=3.9.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.7
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.7
  - aws-sdk-cpp=1.11.458
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - bokeh=3.8.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brukeropusreader=1.3.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.15.2
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charls=2.4.2
  - charset-normalizer=3.4.3
  - click=8.3.0
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.2
  - cpython=3.10.18
  - cycler=0.12.1
  - cytoolz=1.0.1
  - dask=2025.9.1
  - dask-core=2025.9.1
  - dask-image=2024.5.3
  - dav1d=1.2.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dill=0.4.0
  - distributed=2025.9.1
  - docrep=0.3.2
  - double-conversion=3.3.1
  - et_xmlfile=2.0.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - exspy=0.3.2
  - flexcache=0.3
  - flexparser=0.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - fsspec=2025.9.0
  - giflib=5.2.2
  - glib=2.84.0
  - glib-tools=2.84.0
  - graphite2=1.3.14
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - h11=0.16.0
  - h2=4.3.0
  - h5netcdf=1.6.4
  - h5py=3.14.0
  - harfbuzz=11.0.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - hyperspy=2.3.0
  - hyperspy-base=2.3.0
  - hyperspy-gui-ipywidgets=2.1.0
  - hyperspy-gui-traitsui=2.1.1
  - icc_rt=2022.1.0
  - icu=75.1
  - idna=3.10
  - imagecodecs=2024.9.22
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.30.1
  - ipympl=0.9.8
  - ipython=8.37.0
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.9
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - jxrlib=1.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.0
  - lazy-loader=0.4
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.4
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=21.1.2
  - libcrc32c=1.1.2
  - libcurl=8.14.1
  - libdeflate=1.22
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libglib=2.84.0
  - libgoogle-cloud=2.31.0
  - libgoogle-cloud-storage=2.31.0
  - libgrpc=1.67.1
  - libhwloc=2.12.1
  - libhwy=1.3.0
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - liblapack=3.9.0
  - libogg=1.3.5
  - libosqp=0.6.3
  - libparquet=18.1.0
  - libpng=1.6.50
  - libprotobuf=5.28.2
  - libqdldl=0.1.7
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.9.0
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxcb=1.16
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - link-traits=1.0.3
  - llvm-openmp=21.1.2
  - llvmlite=0.45.1
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=3.0.3
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mistune=3.1.4
  - mkl=2023.2.0
  - mkl-service=2.4.1
  - mpmath=1.3.0
  - msgpack-python=1.1.2
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - narwhals=2.7.0
  - natsort=8.4.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook-shim=0.2.4
  - numba=0.62.1
  - numexpr=2.11.0
  - numpy=2.2.6
  - openjpeg=2.5.3
  - openpyxl=3.1.5
  - openssl=3.5.4
  - orc=2.0.3
  - osqp=0.6.7.post3
  - overrides=7.7.0
  - packaging=25.0
  - pandocfilters=1.5.0
  - parso=0.8.5
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.44
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pims=0.7
  - pint=0.24.4
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - ply=3.11
  - pooch=1.8.2
  - prettytable=3.16.0
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pybaselines=1.2.1
  - pycparser=2.22
  - pyface=8.0.0
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pyside6=6.9.0
  - pysocks=1.7.1
  - python=3.10.18
  - python-box=7.3.2
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pywavelets=1.8.0
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qdldl-python=0.1.7.post5
  - qhull=2020.2
  - qt-main=5.15.15
  - qt6-main=6.9.0
  - quaternion=2024.0.12
  - rav1e=0.7.1
  - re2=2024.07.02
  - referencing=0.36.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rosettasciio-base=0.10.0
  - rpds-py=0.27.1
  - ruamel.yaml=0.18.15
  - ruamel.yaml.clib=0.2.12
  - ruff=0.14.0
  - scikit-image=0.25.2
  - scikit-learn=1.7.2
  - scipy=1.15.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - setuptools-scm=9.2.0
  - sip=6.10.0
  - six=1.17.0
  - slicerator=1.1.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.8
  - sparse=0.17.0
  - spectrochempy=0.7.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2021.13.0
  - tblib=3.1.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tifffile=2024.12.12
  - tinycss2=1.4.0
  - tk=8.6.15
  - toml=0.10.2
  - tomli=2.3.0
  - toolz=1.0.0
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - traits=7.0.2
  - traitsui=8.0.0
  - types-python-dateutil=2.9.0.20251008
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - tzlocal=5.3.1
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xarray=2025.6.1
  - xlrd=2.0.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2025.4.0
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
prefix: C:\Users\chengliu\AppData\Local\miniconda3\envs\txm
